/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowroomRouteImport } from './routes/showroom'
import { Route as PurchaseCompleteRouteImport } from './routes/purchase-complete'
import { Route as PhotoBarRouteImport } from './routes/photo-bar'
import { Route as OrderDetailsRouteImport } from './routes/order-details'
import { Route as MyPageRouteImport } from './routes/my-page'
import { Route as HeritageRouteImport } from './routes/heritage'
import { Route as CustomizeYourStoryRouteImport } from './routes/customize-your-story'
import { Route as CustomCollectionRouteImport } from './routes/custom-collection'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutShowroomRouteImport } from './routes/checkout-showroom'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ShowroomRoute = ShowroomRouteImport.update({
  id: '/showroom',
  path: '/showroom',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseCompleteRoute = PurchaseCompleteRouteImport.update({
  id: '/purchase-complete',
  path: '/purchase-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoBarRoute = PhotoBarRouteImport.update({
  id: '/photo-bar',
  path: '/photo-bar',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderDetailsRoute = OrderDetailsRouteImport.update({
  id: '/order-details',
  path: '/order-details',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPageRoute = MyPageRouteImport.update({
  id: '/my-page',
  path: '/my-page',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageRoute = HeritageRouteImport.update({
  id: '/heritage',
  path: '/heritage',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeYourStoryRoute = CustomizeYourStoryRouteImport.update({
  id: '/customize-your-story',
  path: '/customize-your-story',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomCollectionRoute = CustomCollectionRouteImport.update({
  id: '/custom-collection',
  path: '/custom-collection',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutShowroomRoute = CheckoutShowroomRouteImport.update({
  id: '/checkout-showroom',
  path: '/checkout-showroom',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/checkout-showroom': typeof CheckoutShowroomRoute
  '/contact': typeof ContactRoute
  '/custom-collection': typeof CustomCollectionRoute
  '/customize-your-story': typeof CustomizeYourStoryRoute
  '/heritage': typeof HeritageRoute
  '/my-page': typeof MyPageRoute
  '/order-details': typeof OrderDetailsRoute
  '/photo-bar': typeof PhotoBarRoute
  '/purchase-complete': typeof PurchaseCompleteRoute
  '/showroom': typeof ShowroomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/checkout-showroom': typeof CheckoutShowroomRoute
  '/contact': typeof ContactRoute
  '/custom-collection': typeof CustomCollectionRoute
  '/customize-your-story': typeof CustomizeYourStoryRoute
  '/heritage': typeof HeritageRoute
  '/my-page': typeof MyPageRoute
  '/order-details': typeof OrderDetailsRoute
  '/photo-bar': typeof PhotoBarRoute
  '/purchase-complete': typeof PurchaseCompleteRoute
  '/showroom': typeof ShowroomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/checkout-showroom': typeof CheckoutShowroomRoute
  '/contact': typeof ContactRoute
  '/custom-collection': typeof CustomCollectionRoute
  '/customize-your-story': typeof CustomizeYourStoryRoute
  '/heritage': typeof HeritageRoute
  '/my-page': typeof MyPageRoute
  '/order-details': typeof OrderDetailsRoute
  '/photo-bar': typeof PhotoBarRoute
  '/purchase-complete': typeof PurchaseCompleteRoute
  '/showroom': typeof ShowroomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/checkout-showroom'
    | '/contact'
    | '/custom-collection'
    | '/customize-your-story'
    | '/heritage'
    | '/my-page'
    | '/order-details'
    | '/photo-bar'
    | '/purchase-complete'
    | '/showroom'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/checkout-showroom'
    | '/contact'
    | '/custom-collection'
    | '/customize-your-story'
    | '/heritage'
    | '/my-page'
    | '/order-details'
    | '/photo-bar'
    | '/purchase-complete'
    | '/showroom'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/checkout-showroom'
    | '/contact'
    | '/custom-collection'
    | '/customize-your-story'
    | '/heritage'
    | '/my-page'
    | '/order-details'
    | '/photo-bar'
    | '/purchase-complete'
    | '/showroom'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CheckoutShowroomRoute: typeof CheckoutShowroomRoute
  ContactRoute: typeof ContactRoute
  CustomCollectionRoute: typeof CustomCollectionRoute
  CustomizeYourStoryRoute: typeof CustomizeYourStoryRoute
  HeritageRoute: typeof HeritageRoute
  MyPageRoute: typeof MyPageRoute
  OrderDetailsRoute: typeof OrderDetailsRoute
  PhotoBarRoute: typeof PhotoBarRoute
  PurchaseCompleteRoute: typeof PurchaseCompleteRoute
  ShowroomRoute: typeof ShowroomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/showroom': {
      id: '/showroom'
      path: '/showroom'
      fullPath: '/showroom'
      preLoaderRoute: typeof ShowroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-complete': {
      id: '/purchase-complete'
      path: '/purchase-complete'
      fullPath: '/purchase-complete'
      preLoaderRoute: typeof PurchaseCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo-bar': {
      id: '/photo-bar'
      path: '/photo-bar'
      fullPath: '/photo-bar'
      preLoaderRoute: typeof PhotoBarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-details': {
      id: '/order-details'
      path: '/order-details'
      fullPath: '/order-details'
      preLoaderRoute: typeof OrderDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-page': {
      id: '/my-page'
      path: '/my-page'
      fullPath: '/my-page'
      preLoaderRoute: typeof MyPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage': {
      id: '/heritage'
      path: '/heritage'
      fullPath: '/heritage'
      preLoaderRoute: typeof HeritageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize-your-story': {
      id: '/customize-your-story'
      path: '/customize-your-story'
      fullPath: '/customize-your-story'
      preLoaderRoute: typeof CustomizeYourStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-collection': {
      id: '/custom-collection'
      path: '/custom-collection'
      fullPath: '/custom-collection'
      preLoaderRoute: typeof CustomCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-showroom': {
      id: '/checkout-showroom'
      path: '/checkout-showroom'
      fullPath: '/checkout-showroom'
      preLoaderRoute: typeof CheckoutShowroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CheckoutShowroomRoute: CheckoutShowroomRoute,
  ContactRoute: ContactRoute,
  CustomCollectionRoute: CustomCollectionRoute,
  CustomizeYourStoryRoute: CustomizeYourStoryRoute,
  HeritageRoute: HeritageRoute,
  MyPageRoute: MyPageRoute,
  OrderDetailsRoute: OrderDetailsRoute,
  PhotoBarRoute: PhotoBarRoute,
  PurchaseCompleteRoute: PurchaseCompleteRoute,
  ShowroomRoute: ShowroomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
